[package]
name = "cea-708-rewrite"
version = "0.1.0"
authors = ["kushagra <kushgpt08@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
